#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use Cpanel::AdminBin::Serializer ();
use Cpanel::Logger               ();
use Cpanel::PwCache              ();
use Cpanel::LoadFile             ();

my $HOST_API_KEY_FILE = "/root/.cpanel/datastore/cf_api";

my $stdin = <STDIN>;
chomp $stdin;
my ( $uid, $function, $data ) = split( / /, $stdin, 3 );

my $logger = Cpanel::Logger->new();

if ( $function eq 'get_host_api_key' ) {
    my $host_api_key = Cpanel::LoadFile::loadfile($HOST_API_KEY_FILE) or do {
        $logger->info("Failed to load Host API key: $!");
    };
    print $host_api_key;
    exit(0);
}
else {
    print "Invalid function specified to APIKey adminbin";
    exit(1);
}

1; #Ah, perl