#!/bin/bash

#5.x install script is in a different location than 6.x this script routes 5.x -> 6.x upgrades to the correct install script

HOST_KEY=$1
MOD_CF=$2
FORMAL_NAME=$3
INSTALL_MODE=$4

## Verify that the dynamicui files have been removed for Paper Lantern
rm -f /usr/local/cpanel/base/frontend/paper_lantern/dynamicui/dynamicui_CloudFlare.conf
rm -f /usr/local/cpanel/base/frontend/paper_lantern/dynamicui/dynamicui_cloudflare*.conf

(cd ../CloudFlare-CPanel* && mv * ../ && ../cloudflare.install.sh -k $HOST_KEY -n '${FORMAL_NAME}')

