#!/bin/bash

## Remove plugin files
rm -rf /usr/local/cloudflare_cpanel
rm -rf /usr/local/cpanel/base/frontend/x3/cloudflare
rm -rf /usr/local/cpanel/base/frontend/paper_lantern/cloudflare
rm -f /usr/local/cpanel/Cpanel/CloudFlare.pm
rm -f /usr/local/cpanel/etc/cloudflare.json
rm -f /root/.cpanel/datastore/cf_api
rm -f /usr/local/cpanel/bin/cloudflare_update.sh
rm -f /usr/local/cpanel/etc/cloudflare_data.yaml
rm -f /usr/local/cpanel/etc/cloudflare_local.tmpl

## Unregister plugin
/usr/local/cpanel/bin/unregister_cpanelplugin cloudflare.cpanelplugin
rm -f cloudflare.cpanelplugin

## Remove update script
iscf=`crontab -l | grep cloudflare`
if [ "$iscf" != "" ]; then
    crontab -l > c.cur
    sed -i '/cloudflare_update.sh/d' c.cur
    crontab c.cur
fi

## Remove post update call
cfonupgrade=`grep -F "cloudflare_update" /scripts/postupcp`
if [ "$cfonupgrade" != "" ]; then
	sed -i '/cloudflare_update.sh/d' /scripts/postupcp
fi

## Verify that the dynamicui files have been removed for X3 and Paper Lantern
rm -rf /usr/local/cpanel/base/frontend/paper_lantern/dynamicui/dynamicui_CloudFlare.conf
